

## Copyright 2018-present Network Optix, Inc. Licensed under MPL 2.0: www.mozilla.org/MPL/2.0/

FROM ubuntu:20.04
LABEL maintainer "Network Optix <support@networkoptix.com>"

# VMS Server debian package file or URL.
ARG MEDIASERVER_DEB=metavms-server-5.1.3.38363-linux_x64.deb

# VMS Server user and directory name.
ARG COMPANY="networkoptix-metavms"
# Also export as environment variable to use at entrypoint.
ENV COMPANY=${COMPANY}

# Disable EULA dialogs and confirmation prompts in installers.
ENV DEBIAN_FRONTEND noninteractive

# Install package needed for dpkg
RUN apt update && \
    apt install -y \
    dpkg

# Copy deb file to container
COPY ${MEDIASERVER_DEB} /tmp/mediaserver.deb

# Install the deb file
RUN dpkg -i /tmp/mediaserver.deb

# Clean up temporary file
RUN rm /tmp/mediaserver.deb

# Fix permissions.
RUN chown ${COMPANY}: /opt/${COMPANY}/mediaserver/var/

ADD entrypoint.sh /opt/mediaserver/

USER ${COMPANY}
WORKDIR /home/${COMPANY}
# Runs the media server on container start unless argument(s) specified.
ENTRYPOINT ["/opt/mediaserver/entrypoint.sh"]
